export const sourceData = [
  {
    id: 1,
    name: '张三',
    age: 25,
    gender: '男',
    email: 'zhangsan@example.com',
    phone: '13800138000',
    address: '北京市海淀区中关村',
    avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
  },
  {
    id: 2,
    name: '李四',
    age: 30,
    gender: '女',
    email: 'lisi@example.com',
    phone: '13800138001',
    address: '上海市浦东新区',
    avatar: 'https://randomuser.me/api/portraits/women/2.jpg',
  },
  {
    id: 3,
    name: '王五',
    age: 28,
    gender: '男',
    email: 'wangwu@example.com',
    phone: '13800138002',
    address: '广州市天河区',
    avatar: 'https://randomuser.me/api/portraits/men/3.jpg',
  },
  {
    id: 4,
    name: '赵六',
    age: 32,
    gender: '女',
    email: 'zhaoliu@example.com',
    phone: '13800138003',
    address: '深圳市福田区',
    avatar: 'https://randomuser.me/api/portraits/women/4.jpg',
  },
  {
    id: 5,
    name: '钱七',
    age: 29,
    gender: '男',
    email: 'qianqi@example.com',
    phone: '13800138004',
    address: '武汉市洪山区',
    avatar: 'https://randomuser.me/api/portraits/men/5.jpg',
  },
  {
    id: 6,
    name: '孙八',
    age: 27,
    gender: '女',
    email: 'sunba@example.com',
    phone: '13800138005',
    address: '西安市雁塔区',
    avatar: 'https://randomuser.me/api/portraits/women/6.jpg',
  },
  {
    id: 7,
    name: '周九',
    age: 31,
    gender: '男',
    email: 'zhoujiu@example.com',
    phone: '13800138006',
    address: '南京市玄武区',
    avatar: 'https://randomuser.me/api/portraits/men/7.jpg',
  },
  {
    id: 8,
    name: '吴十',
    age: 26,
    gender: '女',
    email: 'wushi@example.com',
    phone: '13800138007',
    address: '重庆市渝中区',
    avatar: 'https://randomuser.me/api/portraits/women/8.jpg',
  },
];
